kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "java-springboot-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/acacrc09/java-springboot-example"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile